# runs on releases (prereleased or released)
# publishes package to test.pypi.org or actual
---
name: Release

on:
  release:
    types:
      - prereleased
      - released

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: hmarr/debug-action@v2

      - uses: actions/checkout@v2

      - name: Build and Publish (Prerelease)
        if: "github.event.release.prerelease"
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.PYPI_TEST_TOKEN }}
          build_format: "sdist"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"

      - name: Build and Publish (Release)
        if: "!github.event.release.prerelease"
        uses: JRubics/poetry-publish@v1.9
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
